# Generated by Django 2.1.7 on 2019-02-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceSystem', '0002_auto_20190222_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='roll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='attendanceSystem.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
