# Generated by Django 2.1.7 on 2019-02-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceSystem', '0003_auto_20190222_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceSystem.Student'),
        ),
    ]
