# Generated by Django 2.1.7 on 2019-02-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceSystem', '0005_auto_20190222_1546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'roll')},
        ),
    ]
